apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-devops-platform
  namespace: cloud-devops
spec:
  replicas: 2

  selector:
    matchLabels:
      app: cloud-devops-platform

  template:
    metadata:
      labels:
        app: cloud-devops-platform

    spec:
      containers:
        - name: cloud-devops-platform
          image: cloud-devops-platform:1.0

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5