apiVersion: v1
kind: Service
metadata:
  name: cloud-devops-platform
  namespace: cloud-devops
spec:
  selector:
    app: cloud-devops-platform

  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 5000

  type: LoadBalancer