apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloud-devops-platform
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - cloud-devops

  selector:
    matchLabels:
      app: cloud-devops-platform

  endpoints:
    - port: http
      path: /metrics
      interval: 15s